#### Data frame is two dimensional
#### Series is one dimensional

In [6]:
# In DataFrame
# each row is represented by "index"
# each column is represented by "column"
# row and column can be numbers or strings
# each column in a DataFrame is a Series

In [7]:
# In Series
# it can have single row or column
# rows are represented by "index"

In [12]:
import pandas as pd
import numpy as np

In [9]:
mylist = [['Apple','Orange'],['Black','red']]
myDF = pd.DataFrame(mylist)
myDF

       0       1
0  Apple  Orange
1  Black     red

In [10]:
# giving custom column labels
myDF = pd.DataFrame(mylist,columns=['Fruits','Colors'])
myDF

  Fruits  Colors
0  Apple  Orange
1  Black     red

In [14]:
#Creating DataFrame using np array
nplist = np.array([[1,2],[3,4],[5,6]])
myDF = pd.DataFrame(nplist)
myDF

   0  1
0  1  2
1  3  4
2  5  6

In [15]:
#Creating DataFrame using Dictionary
# each key will become column label
# each key should have one or more values
mydic = {'Fruit':['Apple','Orange','Banana'],'Color':['Red','Orange','Yellow']}
myDF = pd.DataFrame(mydic)
myDF

    Fruit   Color
0   Apple     Red
1  Orange  Orange
2  Banana  Yellow

In [20]:
# Loading CSV files
# csv file should be on same folder as the notebook is present
myDF = pd.read_csv('Barcelona_rent_price.csv')
myDF

,Year,Trimester,District,Neighbourhood,Average _rent,Price
0,2014,1,Ciutat Vella,el Raval,average rent (euro/month),589.55
1,2014,1,Ciutat Vella,Gothic Quarter,average rent (euro/month),712.79
2,2014,1,Ciutat Vella,la Barceloneta,average rent (euro/month),540.71
3,2014,1,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",average rent (euro/month),673.44
4,2014,1,Eixample,Fort Pienc,average rent (euro/month),736.09
...,...,...,...,...,...,...
4617,2022,2,Sant Marti,Diagonal Mar i el Front Maritim del Poblenou,average rent per surface (euro/m2),17.50
4618,2022,2,Sant Marti,el Besos i el Maresme,average rent per surface (euro/m2),12.20
4619,2022,2,Sant Marti,Provencals del Poblenou,average rent per surface (euro/m2),14.60
4620,2022,2,Sant Marti,Sant Marti de Provencals,average rent per surface (euro/m2),11.90
4621,2022,2,Sant Marti,la Verneda i la Pau,average rent per surface (euro/m2),11.40

In [25]:
newDF=myDF.head()
newDF

,Year,Trimester,District,Neighbourhood,Average _rent,Price
0,2014,1,Ciutat Vella,el Raval,average rent (euro/month),589.55
1,2014,1,Ciutat Vella,Gothic Quarter,average rent (euro/month),712.79
2,2014,1,Ciutat Vella,la Barceloneta,average rent (euro/month),540.71
3,2014,1,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",average rent (euro/month),673.44
4,2014,1,Eixample,Fort Pienc,average rent (euro/month),736.09

In [26]:
#setting index
newDF.set_index('Year')

,Trimester,District,Neighbourhood,Average _rent,Price
Year,,,,,
2014,1,Ciutat Vella,el Raval,average rent (euro/month),589.55
2014,1,Ciutat Vella,Gothic Quarter,average rent (euro/month),712.79
2014,1,Ciutat Vella,la Barceloneta,average rent (euro/month),540.71
2014,1,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",average rent (euro/month),673.44
2014,1,Eixample,Fort Pienc,average rent (euro/month),736.09